export const season = {
    year: String,
    team: String,
    age: Number,
    gp: Number,
    toi_all: Number,
    toi_ev: Number,
    toi_pp: Number, 
    toi_sh: Number,
    evo_gar: Number,
    xevo_gar: Number,
    evd_gar: Number,
    xevd_gar: Number,
    ppo_gar: Number,
    xppo_gar: Number,
    shd_gar: Number,
    xshd_gar: Number,
    off_gar: Number,
    xoff_gar: Number,
    def_gar: Number,
    xdef_gar: Number,
    pen_gar: Number,
    tot_gar: Number,
    xtot_gar: Number,
    qoc: Number,
    qot: Number,
    shoot: Number,
    goals: Number,
    primary_assists: Number,
    secondary_assists: Number,
    points: Number,
    sht_pct: Number,
    fow: Number,
    fol: Number,
}

export const goalie_season = {
    year: String,
    team: String,
    age: Number,
    gp: Number,
    toi_all: Number,
    tot_gar: Number,
    sv_pct: Number,
    gsax: Number,
}

export const player = {
    name: String,
    id: Number,
    seasons: [season],
    position: String,
    shoots: String,
    birthday: String,
    draft_year: Number,
    draft_round: Number,
    draft_overall: Number,
}

export const goalie = {
    name: String,
    id: Number,
    seasons: [goalie_season],
    position: String,
    shoots: String,
    birthday: String,
    draft_year: Number,
    draft_round: Number,
    draft_overall: Number,
}